name: Build fastapi_cicd docker

on:
  push:
    tags:
    - v*

env:
  IMAGE_NAME: fastapi_cicd

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Run tests
  #     run: |
  #       docker build . --file deploy/Dockerfile

  push:
    # needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --file deploy/Dockerfile --tag $IMAGE_NAME
    - name: Log into registry
      run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u ppss1806 --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ppss1806/$IMAGE_NAME

        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
